# -*- coding: utf-8 -*-
"""Parallel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lb7RDgX1tikTrBzYGGITiacV5Su8TDo
"""

import pandas as pd
import time
from concurrent.futures import ThreadPoolExecutor

students_file_path = "students.csv"
fees_file_path = "student_fees.csv"
def read_students_csv():
    return pd.read_csv(students_file_path)
def read_fees_csv():
    return pd.read_csv(fees_file_path)
start_time = time.time()
with ThreadPoolExecutor() as executor:
    future_students = executor.submit(read_students_csv)
    future_fees = executor.submit(read_fees_csv)
    students_df = future_students.result()
    fees_df = future_fees.result()
end_time = time.time()
print(f"Parallel Execution Time: {end_time - start_time:.4f} seconds")